### ISSUE TITLE
Add a footer section

### ISSUE THREAD

**Issue by mrinalstark** [mrinalstark/mrinalProjects#2]
add an creative footer for the project

**Comment by Patil-Mandar** [comment]
Hey @mrinalstark I would like to work on it.

**Comment by mrinalstark** [comment]
Yeah go ahead

**Comment by mrinalstark** [comment]
Before giving a pull request give screen shot here

**Comment by Patil-Mandar** [comment]
![image](https://user-images.githubusercontent.com/80695146/194098801-612b5f80-9c49-4389-9e67-f7c97cfe4bf3.png)

**Comment by Patil-Mandar** [comment]
@mrinalstark you can close this issue.

**Comment by mrinalstark** [comment]
@Patil-Mandar  Nice Work done by him
